---
resources:
- name: dockerfile-repo
  type: git
  source:
    paths: [ "ci/Dockerfile" ]
    branch: feature/pipeline1
    uri: https://github.com/stardog-union/stardog-graviton.git

- name: graviton-repo
  type: git
  source:
    branch: feature/pipeline1
    uri: https://github.com/stardog-union/stardog-graviton.git

- name: ci-docker-image
  type: docker-image
  source:
    repository: buzztroll/graviton-builder
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: stage-bucket
  type: s3
  source:
    bucket: graviton-staging
    regexp: stardog-graviton-(?P<version>.*)
    region_name: {{s3-region}}
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: final-bucket
  type: s3
  source:
    bucket: {{final-bucket}}
    regexp: stardog-graviton-(?P<version>.*)
    region_name: {{s3-region}}
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

jobs:
- name: build-docker
  plan:
  - get: dockerfile-repo
    trigger: true
  - put: ci-docker-image
    params:
      build: dockerfile-repo/ci

- name: build-graviton
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ build-docker ]
      trigger: true
    - get: graviton-repo
      passed: [ build-docker ]
      trigger: true
  - task: make-grav
    image: ci-docker-image
    config:
      platform: linux
      inputs:
      - name: graviton-repo
      outputs:
      - name: build-dir
      run:
        path: sh
        args:
        - -exc
        - |
          x=`pwd`
          ls /usr/local/go/bin
          cp -r graviton-repo /usr/local/src/go/src/github.com/stardog-union/stardog-graviton
          cd /usr/local/src/go/src/github.com/stardog-union/stardog-graviton
          export GOPATH=/usr/local/src/go
          export PATH=/usr/local/go/bin:/usr/local/src/go/bin:$PATH
          make
          make test
          cat etc/version
          ver=`cat etc/version`
          gox -osarch="linux/amd64" -osarch="darwin/amd64" -output=$x/build-dir/$ver/{{.OS}}_{{.Arch}}/stardog-graviton
  - aggregate:
    - put: stage-bucket
      params:
        file: build-dir/*/darwin_amd64/stardog-graviton
    - put: stage-bucket
      params:
        file: build-dir/*/linux_amd64/stardog-graviton

- name: graviton-test
  plan:
  - aggregate:
    - get: graviton-repo
      passed: [ build-graviton ]
    - get: ci-docker-image
      passed: [ build-graviton ]
    - get: stage-bucket
      passed: [ build-graviton ]
      params:
        file: build-dir/*/linux_amd64/stardog-graviton
      trigger: true
  - task: make-env
    image: ci-docker-image
    config:
      platform: linux
      outputs:
      - name: build-dir
      run:
        path: sh
        args:
        - -exc
        - |
          curl -u {{archiveuser}}:{{archivepw}} -o build-dir/stardog-{{stardog-version}}.zip {{stardogurl}}
          echo {{stardog-license}} | base64 -d > build-dir/stardog-license-key.bin
  - task: launch
    image: ci-docker-image
    config:
      platform: linux
      inputs:
      - name: graviton-repo
      - name: build-dir
      - name: stage-bucket
      outputs:
      - name: grav-dir
      run:
        path: graviton-repo/ci/start-cluster.sh
        args:
          - {{run-long-test}} 
          - {{s3-access-key}} 
          - {{s3-secret}}
          - stage-bucket
          - {{stardog-version}}
          - build-dir
          - grav-dir

  - task: load
    image: ci-docker-image
    config:
      platform: linux
      inputs:
      - name: graviton-repo
      - name: grav-dir
      - name: stage-bucket
      run:
        path: graviton-repo/ci/create-db.sh
        args:
          - {{run-long-test}} 
          - {{s3-access-key}}
          - {{s3-secret}}
          - graviton-repo
          - grav-dir
          - stage-bucket
          - {{stardog-version}}
    
  - task: destroy
    image: ci-docker-image
    config:
      platform: linux
      inputs:
      - name: graviton-repo
      - name: grav-dir
      - name: build-dir
      - name: stage-bucket
      run:
        path: graviton-repo/ci/stop-cluster.sh
        args:
          - {{run-long-test}} 
          - {{s3-access-key}}
          - {{s3-secret}}
          - stage-bucket
          - grav-dir
          - build-dir
