---
resources:
- name: dockerfile-repo
  type: git
  source:
    paths: [ "ci/Dockerfile" ]
    branch: feature/pipeline1
    uri: https://github.com/stardog-union/stardog-graviton.git

- name: graviton-repo
  type: git
  source:
    branch: feature/pipeline1
    uri: https://github.com/stardog-union/stardog-graviton.git

- name: ci-docker-image
  type: docker-image
  source:
    repository: buzztroll/graviton-builder
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: build-docker
  plan:
  - get: dockerfile-repo
    trigger: true
  - put: ci-docker-image
    params:
      build: dockerfile-repo/ci

- name: build-graviton
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ build-docker ]
      trigger: true
    - get: graviton-repo
      trigger: true
  - task: make-grav
    image: ci-docker-image
    config:
      platform: linux
      inputs:
      - name: graviton-repo
      outputs:
      - name: build-dir
      run:
        path: graviton-repo/ci/build-graviton.sh
        args:
          - {{s3-access-key}} 
          - {{s3-secret}}
          - graviton-repo
          - build-dir
          - {{stage-bucket}}

- name: graviton-test
  plan:
  - aggregate:
    - get: graviton-repo
      passed: [ build-graviton ]
    - get: ci-docker-image
      passed: [ build-graviton ]
  - task: make-env
    image: ci-docker-image
    config:
      platform: linux
      outputs:
      - name: build-dir
      run:
        path: sh
        args:
        - -exc
        - |
          curl -u {{archiveuser}}:{{archivepw}} -o build-dir/stardog-{{stardog-version}}.zip {{stardogurl}}
          echo {{stardog-license}} | base64 -d > build-dir/stardog-license-key.bin
  - task: launch
    image: ci-docker-image
    config:
      platform: linux
      inputs:
      - name: graviton-repo
      - name: build-dir
      outputs:
      - name: grav-dir
      run:
        path: graviton-repo/ci/start-cluster.sh
        args:
          - {{run-long-test}} 
          - {{s3-access-key}} 
          - {{s3-secret}}
          - {{stardog-version}}
          - build-dir
          - grav-dir

  - task: load
    image: ci-docker-image
    config:
      platform: linux
      inputs:
      - name: graviton-repo
      - name: grav-dir
      run:
        path: graviton-repo/ci/create-db.sh
        args:
          - {{run-long-test}} 
          - {{s3-access-key}}
          - {{s3-secret}}
          - graviton-repo
          - grav-dir
          - {{stardog-version}}
    
  - task: destroy
    image: ci-docker-image
    config:
      platform: linux
      inputs:
      - name: graviton-repo
      - name: grav-dir
      - name: build-dir
      run:
        path: graviton-repo/ci/stop-cluster.sh
        args:
          - {{run-long-test}} 
          - {{s3-access-key}}
          - {{s3-secret}}
          - grav-dir
          - build-dir
